tidalmigrations/machine_stats

- README.md
This PR adds the attributes that are gathered, for both Windows and *nix systems, to the readme.
> Add attributes to readme

- unix/README.md
- windows/README.md
- Removes invalid links
- Corrects the title for “Machine Stats for Unix-like systems”
> Drop invalid links

- unix/README.md
- Improving the Requirements section
- Providing Installation steps
TODO:
> Adding requirements and installation steps

- unix/requirements.txt
- unix/runner
- Ansible updated to 2.9.18
- Code improvements and formatting
- Inline comments
> Update Ansible version

- README.md
Trivial fix to properly align the ascii diagram in the readme.
> Align ascii graphic in readme

- .github/workflows/codeql-analysis.yml
Adds weekly scheduled code scanning.
More info here
https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#configuring-frequency
> Add weekly scheduled code scanning

- .github/dependabot.yml
This will help us keep this code using up to date and supported packages.
More information on how it works here - https://docs.github.com/en/code-security/supply-chain-security/about-dependabot-version-updates
> Add dependabot autoupdate configuration

- unix/src/machine_stats/__init__.py
> Improve ResultCallback and logs

- libvirt/CONTRIBUTING.md
- libvirt/scripts/nested-virtualization/main.sh
This PR updates the nested virtualization VM creation/running script and add the information on how to create a test environment.
> Libvirt test environment

- unix/README.md
- windows/README.md
Several improvements to documentation for both unix and windows Readmes:
- Improve and add info to unix readme
- Add info and improvements to Windows readme
- Add windows troubleshooting section
> Documentation improvements

- windows/README.md
Adds a potential error messsage and solution to the Windows readme.
> Add windows troubleshooting tip for specific error and command

- libvirt/README.md
Mention the use case of KVM in the introduction. to give context on why someone might use it.
Include a full example connection URI in the sample command. helpful if the user isn't familiar.
> virt-stats Readme suggestions

- unix/src/machine_stats/modules/proc_stats.py
This is to help handle errors @przmv encountered during testing of proc_stats
> Improve guards around potential None values

- unix/README.md
- unix/ansible.cfg
- unix/src/machine_stats/plugins/proc_stats.py
Update documentation and example to reflect actual usage
> Remove reference to unused config value

- unix/src/machine_stats/__init__.py
- unix/src/machine_stats/modules/cpu_utilization.py
- unix/src/machine_stats/plugins/cpu_utilization.py
This PR adds a timestamp to the output,
> add timestamp to output

- .github/workflows/pypi-upload.yml
This reverts commit c0673086a75213886af4af50adb97b0c440cb079.
> Revert "Add cURL to trigger publish-ova workflow (#145)"

- .github/workflows/prechecks.yml
- unix/CONTRIBUTING.md
- unix/setup.cfg
This PR adds a linter [flake8](https://flake8.pycqa.org/en/latest/) for all the Python scripts in the `unix/src` folder.
It also contains changes from #182.
> Add linting for MS4Unix

- unix/src/machine_stats/modules/proc_stats.py
Making a small adjustment, causing an unwanted regression
> fix wrongly named dictionary

- .github/workflows/prechecks-unix.yml
- unix/prechecks/rhel8/scripts/rhel8-python-3.10.sh
This PR continues the work done in #199 and #200 and adds a script to run machine stats with Python 3.10 on RHEL8.
> Add RHEL prechecks workflow for Python 3.10

- windows/README.md
Updated some outdated information on ProcessStats. Also added links to guides, and edited general flow of the README.
> Update ProcessStats in README

- .github/workflows/advanced-prechecks-unix.yml
- unix-alpha/CONTRIBUTING.md
- unix-alpha/README.md
- unix-alpha/alpha-description.md
- unix-alpha/setup.py
A few minor changes for the alpha version
- Change the long description and release a new version for this
- Disable RHEL job from advanced prechecks
- Add warnings with readmes since the docs can be inaccurate, especially RHEL/Debian
> Upgrade docs and release a new alpha version

- unix-alpha/alpha-description.md
Adds supported distributions in the long description of the alpha version.
> Add supported distributions in PyPI description

- libvirt/CONTRIBUTING.md
- unix/CONTRIBUTING.md
Re-word the contribuiting docs on how to release a new version for machine stats and virt stats.
> Update docs on how to release a new version
