tidalmigrations/machine_stats

README.md
windows/runner.ps1

This pull request removes dos2unix dependency that was introduced to mitigate a BOM issue, which has seen been handled internally in Tidal Tools.
This reverts commit 123366187c083b0de627d125fd4edfbe2a44153f.
When merged, it will close this open issue - https://github.com/tidalmigrations/machine_stats/issues/5

Revert "dos2unix is a pre-req until tidal-tools is fixed"

---

README.md
unix/README.md
windows/README.md

This PR splits the main `README` file into three `README`s to make them short and scoped:
1. Main `README` with the overview of the project
2. `README` for PowerShell implementation (Machine Stats for Windows)
3. `README` for Python implementation (Machine Stats for Unix-like systems)

Split README into three files

---

unix/main.py

- It makes it possible to provide a custom path to the inventory file (using `hosts` as the default value)
- It makes it possible to use multiple inventory files
- Adds short help message
```console
$ pipenv run stats # reads inventory from $PWD/hosts
$ pipenv run stats /path/to/my/hosts # reads inventory from /path/to/my/hosts
$ pipenv run stats hosts myhosts # reads inventory from hosts and myhosts
$ pipenv run stats --help
usage: pipenv run stats [-h] [FILE [FILE ...]]
positional arguments:
FILE        hosts file
optional arguments:
-h, --help  show this help message and exit
```

Making hosts file(s) configurable via CLI args

---

unix/src/machine_stats/plugins/cpu_utilization.py

```console
$ machine_stats hosts
[
{
"cpu_average": 0.3499311152382123,
"cpu_count": 1,
"cpu_name": "Intel(R) Xeon(R) CPU @ 2.30GHz",
"cpu_peak": 2.509212142481132,
"fqdn": "instance-1.c.tidal-1529434400027.internal",
"host_name": "instance-1",
"10.128.15.196",
"fe80::4001:aff:fe80:fc4"
],
"operating_system": "Debian",
"operating_system_version": "10",
"ram_allocated_gb": 0.5693359375,
"ram_used_gb": 0.2255859375,
"storage_allocated_gb": 9.778318405151367,
"storage_used_gb": 1.8414325714111328
}
]
```
Look for `cpu_sampling_timeout` field.
```console
$ machine_stats hosts
[
{
"cpu_average": 0.3499311152382123,
"cpu_count": 1,
"cpu_name": "Intel(R) Xeon(R) CPU @ 2.30GHz",
"cpu_peak": 2.509212142481132,
"cpu_sampling_timeout": 30,
"fqdn": …
```

Add `cpu_sampling_timeout` field to the final output

---

unix/README.md

Moves the offline installation lower into the readme. Reason is that a new reader will read top to bottom and it is expected most people won't need the offline mode and can move right from install to see what it collects and running it.

Move offline installation lower in the readme

---

unix/src/machine_stats/__init__.py

This PR fixes the regression with JSON output incompatible with Tidal Tools. Thanks @fortran01!
```
{
"servers": [
{                                                                                 
"cpu_average": 0.13370340845604106,                                           
"cpu_count": 1,                                                               
"cpu_name": "Intel(R) Xeon(R) CPU @ 2.30GHz",                                 
"cpu_peak": 0.990099009900991,                                                
"cpu_sampling_timeout": 30,                                                   
"fqdn": "instance-1.c.tidal-1529434400027.internal",                          
"host_name": "instance-1",                                                     …
```

Adding "servers" property to the final JSON output

---

unix/README.md
unix/src/machine_stats/__init__.py

This PR adds the following changes:
- adds the ability to use configuration files
- updates the documentation on how to utilize configuration files
How to verify this PR:
1. Checkout to the `config-file` branch
2. Make sure you're familiar with [`Contributing Guidelines`](https://github.com/tidalmigrations/machine_stats/blob/master/unix/CONTRIBUTING.md) and have `pipenv` and all the Machine Stats for Unix-like systems dependencies installed:
```
pipenv install --dev
```
3. Create the correct `hosts` file (check the [`README`](https://github.com/tidalmigrations/machine_stats/blob/master/unix/README.md) and/or [How to build your inventory](https://docs.ansible.com/ansible/2.9/user_guide/intro_inventory.html))
4. Create configuration file in one of the locations mentioned in the updated …

Enabling custom configuration files

---

unix/src/machine_stats/plugins/cpu_utilization.py

This PR adds the CPU utilization data to the `custom_fields` property, so it would play nice with Tidal Tools and Tidal Migrations API.
```
{
"servers": [
{
"cpu_count": 1,
"cpu_name": "Intel(R) Xeon(R) CPU @ 2.30GHz",
"cpu_average": 0.20447975806933325,
"cpu_peak": 3.164095712377024,
"cpu_sampling_timeout": 30
"fqdn": "instance-1.c.tidal-1529434400027.internal",
"host_name": "instance-1",
"10.128.15.201",
"fe80::4001:aff:fe80:fc9"
],
"operating_system": "Debian",
"operating_system_version": "10",
"ram_allocated_gb": 0.5673828125,
"ram_used_gb": 0.2255859375,
"storage_allocated_gb": 9.778318405151367,
"storage_used_gb": 1.8576221466064453
}
]
}
```
```
{
"servers": [
{
"cpu_count": 1,
"cpu_name": "Intel(R) Xeon(R) CPU @ 2.30GHz",
"custom_fields": {
"cpu_average": …
```

Adding CPU utilization data to the `custom_fields` property

---

windows/runner.ps1

Includes two fixes, that currently prevent execution in a windows environment:
- Generate json file without BOM
- Sync files to tidal with pipe, avoid interactive prompts

Fixes for windows machine stats

---

windows/README.md
windows/runner.ps1

1. Use `Write-Host` for information messages instead of `Write-Output` which can be piped
2. Remove saving data to a file. If it's needed it can be done by redirection: `.\runner.ps1 > servers.json`
3. Update `README` with the information of how to pipe the output to `tidal sync servers`

Make Machine Stats for Windows output JSON

---

windows/server_stats.ps1

Previously alive time would print as float, `1.0`, this caused parsing
errors to show up in tidal tools. This also seems to go against
Powershell docs where [Math]::Round should have turned that into
`1`. 
Instead we have to switch to casting the float into an int which
guarantees that the value won't have a trailing zero.

Cast time into int to ensure proper formatting in json

---

unix/src/machine_stats/__init__.py

This PR sets the following configuration parameters as defaults:
```
host_key_checking = False
gather_timeout = 180
```
So, there's no need to explicitly state the above values in [Machine Stats configuration file](https://github.com/tidalmigrations/machine_stats/tree/master/unix#configuration).

Setting default configuration parameters

---

unix/src/machine_stats/__init__.py

This PR introduces the hot fix for the default configuration values.
`os.environ` is a mapping object where keys and values are **strings** that represent the process environment, that's why the values were changed into strings.

Fix default configuration values types

---

windows/README.md
windows/runner.ps1

1. Adds `-UserName` parameter instead of the hardcoded one
2. Adds `-ServersPath` parameter instead of looking for `servers.txt` in the `$PWD`
3. Adds inline usage documentation (`PS> help runner.ps1`)
4. Updates the README to reflect the above changes

Make UserName and ServersPath configurable

---

libvirt/README.md
libvirt/src/virt_stats/__init__.py

1. Adds `cpu_count` to the final JSON output
2. Adds `ram_allocated_gb` to the final JSON output
3. Adds `ram_used_gb` to the final JSON output
4. Updates the `README`
Sample output
```json
[
{
"cpu_count": 2,
"host_name": "debian",
"192.168.122.124"
],
"ram_allocated_gb": 3.85,
"ram_used_gb": 0.08
}
]
```
[![asciicast](https://asciinema.org/a/1lkMfZ17iH65T4DH40Yu3WqCH.svg)](https://asciinema.org/a/1lkMfZ17iH65T4DH40Yu3WqCH)

Virt-Stats: adding CPU count and RAM allocated and used (GB)

---

unix/src/machine_stats/modules/proc_stats.py
unix/src/machine_stats/plugins/proc_stats.py

This adds getting the username using the first column, the "Real" column name, from uid in the status file.
More information can be found in [Chapter 1](https://www.kernel.org/doc/html/latest/filesystems/proc.html#chapter-1-collecting-system-information) in the status file sections.

Capture username for running processes

---

windows/runner.ps1
windows/save_password.ps1
windows/server_stats.ps1

CPU utilization feature relies on WinRM approach as for now, so this information is not available when `-NoWinRM` is specified.
Getting process statistics relies on WinRM approach, so this information is not available when `-NoWinRM` is specified.

Adding NoWinRM and ProcessStats parameters

---

.gitignore
libvirt/src/virt_stats/__init__.py

- Adds `storage_allocated_gb` to the final JSON output
- Adds `storage_used_gb` to the final JSON output
Sample output:
```json
[
{
"cpu_count": 1,
"host_name": "debian",
"192.168.122.80"
],
"ram_allocated_gb": 0.96,
"ram_used_gb": 0.06,
"storage_allocated_gb": 2.0,
"storage_used_gb": 0.61
}
]
```

virt-stats: storage information

---

unix/src/machine_stats/modules/cpu_utilization.py
unix/src/machine_stats/plugins/cpu_utilization.py

- Adds `--cpu-utilization-only-value` flag
Without that flag, Machine Stats will provide `peak` and `average` values for CPU utilization, with the flag set, it will only output the value:
```
machine_stats --cpu-utilization-only-value
{
"servers": [
{
"cpu_count": 1,
"cpu_name": "Intel(R) Xeon(R) CPU @ 2.30GHz",
"custom_fields": {
"cpu_sampling_timeout": 30,
"cpu_utilization": 0.5
},
"fqdn": "nested-host.c.machine-stats-lab.internal",
"host_name": "nested-host",
"192.168.122.1",
"10.128.0.30",
"fe80::4001:aff:fe80:1e"
],
"operating_system": "Debian",
"operating_system_version": "10",
"ram_allocated_gb": 3.607421875,
"ram_used_gb": 0.4765625,
"storage_allocated_gb": 9.778318405151367,
"storage_used_gb": 3.032133102416992
}
]
}
```

Adding `--cpu-utilization-only-value` flag to Machine Stats for Unix-like Systems

---

windows/server_stats.ps1

This PR introdoces the following changes:
1. Change script block `$ProcessStats` parameter type from `switch` to `bool`.
Switch parameters are excluded from positional parameters by default, but `ArgumentList` passes only positional parameters to `ScriptBlock`'s of `Invoke-Command` or `Start-Job`.

fix(windows): change param type to bool

---

windows/runner.ps1
windows/server_stats.ps1

This PR introduces the following changes to Machine Stats for Windows:
1. Adds configurable `-CpuUtilizationTimeout` parameter
2. Fixes issue with CPU utilization custom fields and `MemberAlreadyExists` error

CPU utilization timeout parameter

---

.github/workflows/pypi-upload.yml

This PR adds a step in the release machine_stats version workflow to trigger the [publish-amis](https://github.com/tidalmigrations/Infrastructure-templates/blob/main/.github/workflows/publish-images.yml) workflow.

Trigger publish-ami workflow

---

windows/runner.ps1
windows/server_stats.ps1

This PR adds `-CpuUtilizationOnlyValue` param to Machine Stats for Windows. When the param is set it will output only CPU utilization value and not peak and average values.
~This PR should be merged after #127 and updated correspondingly (i.e replace the hard-coded `30` with `$CpuUtilizationTimeout`).~

Adding `-CpuUtilizationOnlyValue` param

---

.github/workflows/pypi-upload.yml

This PR adds a step in the release machine_stats version workflow to trigger the [publish-ova](https://github.com/tidalmigrations/preconfigured-ova/blob/main/.github/workflows/publish-ova-image.yml) workflow.

Trigger publish-ova workflow

---

unix/src/machine_stats/modules/proc_stats.py

In some cases when the proc files deviate from the conventional unix file patterns and 'break', it can cause issues in machine stats to parse and return the running processes. (The 'error' thrown here about the sym link, is actually normal behaviour for 'files' in proc). This PR fixes that. Fix here is to catch all exceptions when resolving the file paths in `/proc` and ignore those files.
current:
new:

Skip process proc files if errors hit resolving path

---

windows/README.md

Clarified that the `servers.txt` file takes _IP addresses_ not _hostnames_. Added mention that you can use public IPv4 DNS instead to analyze machines over the internet.
Also added additional section to #troubleshooting on server name resolution errors.

Updated MS4W Docs

---

windows/runner.ps1

Added 2 new parameters to the MS4W `runner.ps1` script, which allows the user to specify the location of the password file and the `server_stats.ps1` script block. 
These are 
- `SecurePwdFilePath`
- `ServerStatsPath`
Previously these were hard-coded to only look in the current directory, which would work when running MS4W from its directory but would fail when running in a scheduled job since these are not invoked from that directory.
When these parameters are not specified, they default to the current directory, maintaining the original behaviour.
For a full rundown on how to run MS4W in a scheduled job, check out [this document](https://docs.google.com/document/d/1-njAnGHf4R0LLXUgu19_oUDNuUlIDoRGUkMcTH4zczc/edit?usp=sharing).

MS4W: Fix hard-coded paths

---

windows/runner.ps1
windows/server_stats.ps1

Added a timestamp to the output when using the `-CPUUtilizationOnlyValue` flag. 
When using this flag MS4W will take 2 readings, spaced out by the amount of time specified in the `-CpuUtilizationTimeout` flag. The result is the average of these two readings. To calculate this average, the property `TimeStamp_Sys100NS` is read from the subject machine in LDAP time. 
This PR adds the first of these values to the output, converted into a human readable format. The intention is to allow us to get the closest possible time to when CPU utilization is read. 
The name of the custom field and the format of the timestamp are exactly the same as the equivalent in machine stats for Unix. The timestamp is always UTC regardless of the timezone of the controller or subject machines.
Here's a sample …

Add CPU Utilization Timestamp

---

.github/workflows/prechecks-unix.yml
.github/workflows/prechecks-windows.yml

This PR separates the prechecks workflow for Unix and Windows with an updated trigger to only fire up the workflow if the changes are in the relevant folder. It also checks if all the dependencies can be installed with a successful test run of machine stats. This will help us validate changes from dependabot without even running machine stats locally with the new dependencies.

Ubuntu: Check dependencies installation and machine stats' test run

---

windows/runner.ps1
windows/server_stats.ps1

Previously, the logic to read a subject machine with WMI was never used because of an incorrect if clause. This clause would always equate to false because of a typo, and it was only possible to use the WinRM logic.
This PR also passes the `NoWinRM` bool to `server_stats` directly. Previously, there was logic in `server_stats` that tried to ascertain whether we're using the `-NoWinRM` flag by checking that the current computer is not 'localhost' or the had the same hostname as what's being operated on from the `servers.txt` file. 
As this file can take many values (private IP, full DNS address, etc), this logic is unreliable, and it makes more sense that we can tell whether or not we're using the `-NoWinRM` option by simply passing this same option in as an argument to the script block. …

Fix -NoWinRM flag

---

windows/runner.ps1

Before attempting to read the user's server inventory, MS4W will attempt to `Invoke-Command` (WinRM) on the local machine, using the credentials provided for the subject machines, to get the name of the current user. This name is then printed to the console and isn't used anywhere else.
If you're working on a controller machine that doesn't have the same credentials as your subject machines, Invoke-Command will log an error message to the console before continuing on to successfully read your servers. This is confusing behavior.
This PR wraps this logic in a try-catch and catches the specific error thrown in this case. An alternative would be to remove the logic entirely, as this behavior doesn't mirror MS4U and is arguably unneccessary.

Catch error reading local user with WinRM

---

windows/server_stats.ps1

The logic which runs when the `-ProcessStats` flag is used contained invalid single quote characters. This lead to errors like this:
This PR simply swaps them out for the correct characters, and the feature works normally.
This resolves #194 .

Replaced incorrect quotation characters in ProcessStats logic

---

.github/workflows/advanced-prechecks-unix.yml
.github/workflows/default-prechecks-unix.yml
.github/workflows/prechecks-unix.yml
.github/workflows/prechecks-windows.yml
unix/CONTRIBUTING.md

The prechecks workflow for Unix was set to trigger on ANY pull request. This can cause multiple runs of the workflow because it can also get triggered by adding more commits in an open PR. The workflow checked linting and ran machine stats' to see it's working in Ubuntu and RHEL for Python version 3.6 to 3.10. The latter part takes of the workflow takes a while to finish the execution**.
Since we will only want to run the latter part of the workflow with PRs where we think it might be introducing breaking changes (i.e., upgrading ansible version), this PR separates the workflow in 2
- Default prechecks: Checks linting
- Advanced prechecks: Runs machine stats for Ubuntu and RHEL
With the changes in this PR, the default precheck will run as usual but **to run the advanced workflow, you will …

Add default and advanced prechecks workflows for Unix

---

.github/workflows/pypi-upload.yml
libvirt/CONTRIBUTING.md
libvirt/setup.cfg
libvirt/setup.py
unix/CONTRIBUTING.md
unix/setup.cfg
unix/setup.py

This PR removes the previous approach of using `bump2version` and replaces it with tags. With this, you won't need a dev setup to release a new machine stats version.
To make a new release, simply create a tag on the `master` branch and the `pypi-upload` GitHub Workflow will take care of the rest.

Release Machine Stats main using tags

---

.github/workflows/advanced-prechecks-unix.yml
unix-alpha/.gitignore
unix-alpha/Pipfile
unix-alpha/Pipfile.lock
unix-alpha/setup.py

Upgrades to the latest ansible version (5.6.0) for the alpha version.

Upgrade to Ansible 5.6.0 for alpha

---

unix/src/machine_stats/__init__.py

New output when running with -m, matches new TMP API implimentation.
```
{
"measurements": [
{
"external_timestamp": "2022-08-17 15:21:07",
"field_name": "cpu_utilization_timeseries",
"measurable": {
"host_name": "ip-172-31-47-90"
},
"measurable_type": "server",
"value": 0.0
}
]
}
```

Added timestamp when running with -m flag

---

windows/runner.ps1
windows/server_stats.ps1

Added the `-Measurements` flag to MS4W. Running with this flag will output the result in a data structure suitable for piping to the TMP /measurements API. 
The intended purpose of this flag is for taking point in time CPU utilization data. Therefore, running with this flag will automatically set `-CpuUtilizationOnlyValue` and `-CpuUtilizationTimeout 1`. This means you don't need to explicitly include these flags in the command when running `-Measurements`. I recommend we make this change to MS4U also. 
The command is as follows:
`./runner.ps1 -UserName Administrator -Measurements`
For piping straight to TMP:
`./runner.ps1 -UserName Administrator -Measurements | tidal request -X POST /api/v1/measurements/import`
This PR also removes the following unnecessary properties from the response …

MS4W -Measurements

---

unix/Pipfile.lock
unix/dev-requirements.txt
unix/requirements.txt

Updates the dependencies for the machine stats Unix package. I have a plan in motion to check it's validity against the following target subject instances:
| Distribution | Python version | Notes               |
|--------------|----------------|---------------------|
| Ubuntu 18    | Python 3.6     | Controller instance |
| Ubuntu 16    | Python 2.6     | Subject instance    |
| Ubuntu 16    | Python 2.7     | Subject instance    |
| Ubuntu 16    | Python 3.5     | Subject instance    |
| Ubuntu 18    | Python 3.6     | Subject instance    |
| Ubuntu 18    | Python 3.7     | Subject instance    |
| Ubuntu 18    | Python 3.8     | Subject instance    |
| Ubuntu 18    | Python 3.9     | Subject instance    |
| Ubuntu 18    | Python 3.10    | Subject instance    |
| RHEL8        | Python 2.6 …

Update dependencies for MS4U

---

windows/README.md

Update readme to show all fields that are captured and stored by default.
Custom fields do not need to be created.

Update readme to match behaviour

---

LICENSE
README.md
SECURITY.md
libvirt/README.md
libvirt/setup.py
unix/README.md
unix/setup.py
windows/README.md
windows/runner.ps1

Content changes to replace the reference to `tidalmg.com` with `tidal.cloud`, Tidal Migrations with Tidal, logos, and reference to Accelerator where appropriate.

Content changes to tidal.cloud

---

windows/server_stats.ps1

Switch MS4W CPU utilization timestamp from 12 to 24 hour format
